import type { ComponentNode, GeneratedComponent } from "@/types";
import { buildPreviewFromTree } from "@/tools/preview-builder";

export interface StackBlitzProject {
  title: string;
  description: string;
  template: "node";
  files: Record<string, string>;
}

export interface StackBlitzProjectOptions {
  previewHtml?: string;
  componentTree?: ComponentNode;
}

function resolvePreviewHtml(
  projectName: string,
  options?: StackBlitzProjectOptions
): string | null {
  if (options?.previewHtml?.trim()) return options.previewHtml;
  if (options?.componentTree) return buildPreviewFromTree(options.componentTree, projectName);
  return null;
}

/** StackBlitz project: full live preview in index.html + exported React components in src/ */
export function buildStackBlitzProject(
  components: GeneratedComponent[],
  projectName: string,
  options?: StackBlitzProjectOptions
): StackBlitzProject {
  const previewHtml = resolvePreviewHtml(projectName, options);

  const files: Record<string, string> = {
    "package.json": JSON.stringify(
      {
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
        devDependencies: { vite: "^6.0.3" },
      },
      null,
      2
    ),
    "vite.config.js": `import { defineConfig } from 'vite'
export default defineConfig({ server: { open: true } })`,
    "README.md": `# ${projectName}

Generated by BridgeView AI.

- **Preview**: Open \`index.html\` — full maritime dashboard (matches Live Preview)
- **Components**: Exported React source files in \`src/\`
`,
  };

  // Full dashboard preview — same HTML as the Live Preview tab
  if (previewHtml) {
    files["index.html"] = previewHtml;
  } else {
    files["index.html"] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div class="p-8 text-center text-gray-500">No preview available</div>
</body>
</html>`;
  }

  // Include all generated React components for code export
  for (const comp of components) {
    const path = comp.filename.startsWith("src/")
      ? comp.filename
      : `src/${comp.filename}`;
    files[path] = comp.code;
  }

  return {
    title: projectName,
    description: "Generated by BridgeView AI — maritime UI dashboard preview",
    template: "node",
    files,
  };
}
